; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-s3-n4r2, esp32-s3-n8r8, esp32-s3-n16r8

[env_common]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.36/platform-espressif32.zip
framework = arduino
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.f_psram = 80000000L
board_build.filesystem = littlefs
board_build.littlefs_display_name = LittleFS
upload_protocol = esptool
upload_speed = 921600
build_type = release
build_unflags = -std=gnu++11
common_build_flags = 
	-std=gnu++2a
	-fno-exceptions
	-Wall
	-Wextra
	-O2
	-D BOARD_HAS_PSRAM
	-D ARDUINO_RUNNING_CORE=1
	-D ARDUINO_EVENT_RUNNING_CORE=1
	-D WIFI_TASK_PRIORITY=5
	-D AUDIOTASK_CORE=0
	-D AUDIOCONTROLTASK_PRIO=4
	-D UI_TASK_PRIO=2
	-D DEF_SPI_FREQ=80000000UL
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=1
	-D CORE_DEBUG_LEVEL=2
	-D CONFIG_ARDUHAL_LOG_COLORS=1
	-fdiagnostics-color=always
extra_scripts = pre:copy_glcdfont.py
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time, colorize
monitor_dtr = 0
monitor_rts = 0
lib_deps = 
	adafruit/Adafruit BusIO
	adafruit/Adafruit GFX Library

[env:esp32-s3-n4r2]
extends = env_common
board = esp32-s3-n4r2
board_build.arduino.memory_type = qio_qio
board_build.psram_type = qio
board_build.flash_mode = qio
board_upload.flash_size = 4MB
board_build.partitions = partitions_4MB.csv
board_upload.maximum_size = 1966080
build_unflags = ${env_common.build_unflags}
build_flags = ${env_common.common_build_flags}

[env:esp32-s3-n8r8]
extends = env_common
board = esp32-s3-n8r8
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_build.flash_mode = qio
board_upload.flash_size = 8MB
board_build.partitions = partitions_8MB.csv
board_upload.maximum_size = 3145728
build_unflags = ${env_common.build_unflags}
build_flags = ${env_common.common_build_flags}

[env:esp32-s3-n16r8]
extends = env_common
board = esp32-s3-n16r8
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.partitions = partitions_16MB.csv
board_upload.maximum_size = 3145728
build_unflags = ${env_common.build_unflags}
build_flags = ${env_common.common_build_flags}
